name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: property-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --passWithNoTests

  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: property-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./property-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
